#!/bin/zsh
export PATH="$PATH:$HOME/.local/bin/"

export _JAVA_AWT_WM_NONREPARENTING=1

export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export ZDOTDIR="$HOME/.config/zsh"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WGETGHOME="$XDG_DATA_HOME/wget"


#export EDITOR="nvim"
#export TERMINAL="st"
#export BROWSER="firefox"
#export READER="zathura"
#export PDF_READER="zathura"
#export FILE="vifm"
